### PR TITLE
change SuiInteger to SuiString based on the builders in sync and async clients

### PR DESCRIPTION
**Pull request by milade3013**
there was a problem in this codes. i got error when i tried to transfer sui. For example, the transfer_sui_txn function needed sui integer parameter. but TransferSui builder class needed sui string.

### CODE REVIEW

**Comment by milade3013** [comment]
@FrankC01.
hi dear FrankC01. i faced a problem in the client codes. i got error when i tried to transfer sui. For example, the transfer_sui_txn function needed sui integer parameter. but TransferSui builder class needed sui string. so i changed it and the problem solved for me. 
It will me my pleasure if you check this PR. thank you

**Comment by FrankC01** [comment]
@milade3013 

1. There are conversions that happen down in the evaluation of the argument level. This passed without error and Sui was transferred:

https://suiexplorer.com/txblock/BPq28ZLfe4bjnEUcxonYTKxhprkNa7cKJHSJNLt3adap?network=devnet

```python
    result = client.transfer_sui_txn(
        signer=cfg.active_address,
        sui_object_id=ObjectID(
            "0x0c6031175ce2c33edd13563ac94ad3c5007f170a7a7d69448ead7b76153c9470"
        ),
        gas_budget=10000000,
        recipient=SuiAddress(
            "0xa9fe7b9cab7ce187c768a9b16e95dbc5953a99ec461067a73a6b1c4288873e28"
        ),
        amount=1000000000,
    )
```

2. With the 0.27.0 release (today) I am `deprecating` all `unsafe_` calls in favor of using the `pysui SuiTransaction` builder.

What error did you get?

**Comment by milade3013** [comment]
@FrankC01 
the code to transfer:
    amount = SuiInteger(1000000)
    gas_budget = SuiInteger(10000000)
    transaction = await client.transfer_sui_txn(
                              signer=signer_address,                                         
                              sui_object_id=ObjectID("0xff164bfe0bae3df47cb6abcd95cf73a1d34b2ccb938e67e45b9eaf46f6134947"), 
                              gas_budget=gas_budget,
                              recipient=recipient_address,
                              amount=amount
                              )
    print(transaction.result_string, transaction.result_data, transaction.is_ok())
    
error:
invalid type: integer `10000000`, expected a string at line 1 column 190 None False
i changed the SuiInteger to SuiString in transfer_sui_txn params and it the transaction sent.
https://suiexplorer.com/txblock/XiJKgAWqYWVnWhNFwEBtY6oRrJy21cmrTJFiqG41QUa?network=devnet

**Comment by milade3013** [comment]
@FrankC01
i changed 
amount = SuiInteger(1000000)
gas_budget = SuiInteger(10000000)
to 
amount = 1000000
gas_budget = 10000000
and the transaction sent without changing SuiInteger to SuiString.

**Comment by FrankC01** [comment]
> @FrankC01 i changed amount = SuiInteger(1000000) gas_budget = SuiInteger(10000000) to amount = 1000000 gas_budget = 10000000 and the transaction sent without changing SuiInteger to SuiString.

I will try with async but, again, these are being deprecated

**Comment by milade3013** [comment]
@FrankC01
I see. 
Thank you very much.

Regards

**Pull request closed without merging**
